In [3]:
import numpy as np
array = [1.84,1.60]
heights = np.array(array)
heights

array([1.84, 1.6 ])

In [4]:
array = [93.1, 54.2]
weights = np.array(array)
weights

array([93.1, 54.2])

In [6]:
bmis = weights / heights ** 2
bmis

array([27.49881853, 21.171875  ])

In [7]:
for val in np.nditer(bmis):
    print(val)

27.498818525519845
21.171874999999996
